/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    APIKeys: typeof import('./src/components/settings/APIKeys.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    ArrayInput: typeof import('./src/components/ArrayInput.vue')['default']
    ArrayInputWithOptions: typeof import('./src/components/ArrayInputWithOptions.vue')['default']
    Backup: typeof import('./src/components/settings/Backup.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ContainerDialog: typeof import('./src/components/ContainerDialog.vue')['default']
    Docker: typeof import('./src/components/settings/Docker.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MonitorHistory: typeof import('./src/components/settings/MonitorHistory.vue')['default']
    NetworkInput: typeof import('./src/components/NetworkInput.vue')['default']
    Notifications: typeof import('./src/components/settings/Notifications.vue')['default']
    Proxies: typeof import('./src/components/settings/Proxies.vue')['default']
    ReverseProxy: typeof import('./src/components/settings/ReverseProxy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    Tags: typeof import('./src/components/settings/Tags.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
    Uptime: typeof import('./src/components/Uptime.vue')['default']
  }
}
