name: Close Incorrect Issue

on:
  issues:
    types: [opened]

jobs:
  close-incorrect-issue:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
    - uses: actions/checkout@v3

    - name: Close Incorrect Issue
      run: node extra/close-incorrect-issue.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.number }} ${{ github.event.issue.user.login }}
